name: Bug report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and steps to reproduce
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: App version/commit
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      render: shell

