import 'package:afiyyah_connect/features/health_input/model/periksaklinikstatus_model.dart';
import 'package:flutter/material.dart';

class PendataanKesehatanModel {
  final String? pendataanId;
  final DateTime? createdAt;
  final List<String> keluhan;
  final DateTime mulaiSakit;
  final String santriId;
  final PeriksaKlinikStatus? statusPeriksa;
  final TimeOfDay? waktuMulaiSakit;
  final String? userId;

  PendataanKesehatanModel({
    this.pendataanId,
    this.createdAt,
    required this.keluhan,
    required this.mulaiSakit,
    required this.santriId,
    this.statusPeriksa,
    this.waktuMulaiSakit,
    this.userId,
  });

  Map<String, dynamic> toJson() {
    // Helper to format TimeOfDay to 'HH:mm:ss' string
    String? formatTimeOfDay(TimeOfDay? time) {
      if (time == null) return null;
      final hour = time.hour.toString().padLeft(2, '0');
      final minute = time.minute.toString().padLeft(2, '0');
      return '$hour:$minute:00';
    }

    return {
      // pendataan_id is generated by db
      // created_at is generated by db
      'keluhan': keluhan,
      'mulai_sakit': mulaiSakit.toIso8601String(),
      'santri_id': santriId,
      'status_periksa': statusPeriksa?.name,
      'waktu_mulai_sakit': formatTimeOfDay(waktuMulaiSakit),
      'user_id': userId,
    };
  }
}
